import NavBar from "@/components/layout/NavBar";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/layout/Footer";
import ReduxProvider from "@/store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function getProducts() {
  const res = await fetch("http://localhost:3000/api/products", {
    next: { revalidate: 60 },
  });
  const products = await res.json();
  return products;
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const products = await getProducts();
  const productsArray = products.products;

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <NavBar products={productsArray} />
          {children}
          <Footer products={productsArray} />
        </ReduxProvider>
      </body>
    </html>
  );
}
